### ISSUE TITLE
Need help in automating windows application using winium driver with selenium

### ISSUE THREAD

**Issue by simran4** [lukeis/selenium-gcode-issue-archive#8790]
Hi all,
Please help me with the windows application automation. I am unable to track the element with inspect element tool of windows or any other tool. Unable to track Flash object, Please send me the details to automate using which framework and how to track this image object. Which i already tried to do with sikuli tool which is unsuccessful again.

**Comment by alterhu2020** [comment]
you can try to use AutoIt for windows application testing ,selneium is only worked for browser testing ,which  implements the http json wired protocol ...

**Comment by simran4** [comment]
Hi i used even autoit. Unable to trace the login button as it is flash object. Instead the finder tool is tracing the entire window .please check screenshot
![1](https://cloud.githubusercontent.com/assets/23374599/20169838/b0502e6a-a74f-11e6-8a70-a3eb74ddd5d1.png)

**Comment by alterhu2020** [comment]
First you can try to use AutoIt Recorder to recorder the operation for your login behavior ,then you replay the recorded script ,if that still not works ,maybe you need to try another third part tool  (HP QTP or test complete.etc) 
Otherwise i think there's no good solution for your windows application testing.

**Comment by simran4** [comment]
i tried the recording tool as well.. Even i tried free version of test complete it s the same for all. 
I am looking only for free version so. If you have any other suggestion

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
